# Generated by Django 3.0.4 on 2020-03-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banco',
        ),
        migrations.DeleteModel(
            name='ciudad',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Consumo',
        ),
        migrations.DeleteModel(
            name='departamento',
        ),
        migrations.DeleteModel(
            name='EstadoFactura',
        ),
        migrations.DeleteModel(
            name='EstadoSucursalCliente',
        ),
        migrations.DeleteModel(
            name='EstadoUsuario',
        ),
        migrations.DeleteModel(
            name='Facturacion',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='SubEstacion',
        ),
        migrations.DeleteModel(
            name='SucursalCliente',
        ),
        migrations.DeleteModel(
            name='Tarifa',
        ),
        migrations.DeleteModel(
            name='tipoCliente',
        ),
        migrations.DeleteModel(
            name='TipoIdentificacion',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
        migrations.DeleteModel(
            name='Transformador',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='UsuarioEstadoVigencia',
        ),
    ]
