# Generated by Django 3.0.4 on 2020-05-03 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0007_auto_20200501_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoSucursalCliente',
        ),
        migrations.AlterField(
            model_name='banco',
            name='cnsctvo_cdd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Ciudad'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='cnsctvo_dprtmnto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Departamento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnsctvo_tpo_clnte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.TipoCliente'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cnsctvo_cdd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Ciudad'),
        ),
        migrations.AlterField(
            model_name='subestacion',
            name='cnsctvo_cdd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Ciudad'),
        ),
        migrations.AlterField(
            model_name='transformador',
            name='lngtd',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transformador',
            name='lttd',
            field=models.FloatField(),
        ),
    ]
