# Generated by Django 3.0.3 on 2020-04-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(max_length=1000)),
                ('url', models.CharField(max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaPublicacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
