# Generated by Django 3.0.3 on 2020-04-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='contenido',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='articulo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
