# Generated by Django 3.0.3 on 2020-05-07 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmbre_bnco', models.CharField(max_length=50)),
                ('drccn', models.CharField(max_length=150)),
                ('tlfno', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmbre_cdd', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmro_idntfccn', models.CharField(max_length=11)),
                ('prmr_nmbre', models.CharField(max_length=50)),
                ('prmr_aplldo', models.CharField(max_length=50)),
                ('fcha_ncmnto', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwh', models.IntegerField(default=0)),
                ('prdo_cnsmo', models.CharField(default='', max_length=50)),
                ('obsrvcn', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlr_cnsmo', models.FloatField(default=0.0)),
                ('vlr_intrss_mra', models.FloatField(default=0.0)),
                ('vlr_rcnxn', models.FloatField(default=0.0)),
                ('vlr_ttl', models.FloatField(default=0.0)),
                ('fcha_lmte_pgo', models.DateField()),
                ('cntdd_fctrs_pndts', models.IntegerField(default=0.0)),
                ('fcha_crte_srvco', models.DateField()),
                ('obsrvcn', models.CharField(default='', max_length=150)),
                ('cnsctvo_cnsmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Consumo')),
            ],
        ),
        migrations.CreateModel(
            name='SubEstacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('drccn', models.CharField(max_length=150)),
                ('tlfno', models.CharField(max_length=50)),
                ('lngtd', models.FloatField(default=0)),
                ('lttd', models.FloatField(default=0)),
                ('estdo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlr_kwh', models.FloatField(default=0)),
                ('inco_vgca', models.DateTimeField(auto_now_add=True)),
                ('obsrvcn', models.CharField(max_length=150)),
                ('estdo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dscrpcn_tpo_clnte', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dscrpcn_tpo_idntfcn', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transformador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grpo_cnxn', models.CharField(max_length=20)),
                ('tnsn_prmra', models.IntegerField(default=0)),
                ('tnsn_mxma_srvco', models.IntegerField(default=0)),
                ('tnsn_scndra', models.IntegerField(default=0)),
                ('ptnca_nmnl', models.IntegerField(default=0)),
                ('intnsdd_nmnl_prmra', models.IntegerField(default=0)),
                ('tnsn_crto_crcto', models.IntegerField(default=0)),
                ('rlcn_trnsfrmcn', models.IntegerField(default=0)),
                ('lngtd', models.FloatField(default=0)),
                ('lttd', models.FloatField(default=0)),
                ('estdo', models.BooleanField(default=True)),
                ('obsrvcn', models.CharField(default='', max_length=150)),
                ('sub_estcn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.SubEstacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlr_pgdo', models.FloatField(default=0)),
                ('fcha_pgo', models.DateTimeField(auto_now_add=True)),
                ('obsrvcn', models.CharField(default='', max_length=150)),
                ('cnsctvo_fctra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='factura.Facturacion')),
                ('idntfccn_bnco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.Banco')),
                ('nmro_unco_idntfccn_usro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='facturacion',
            name='cnsctvo_trfa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Tarifa'),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrt_scl', models.CharField(default='0', max_length=2)),
                ('drccn', models.CharField(default='', max_length=150)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='consumo',
            name='idntfccn_cntrto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Contrato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tpT_clnte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.TipoCliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tpo_idntfcn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.TipoId'),
        ),
    ]
