# Generated by Django 3.0.3 on 2020-05-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_auto_20200507_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fcha_ncmnto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tpT_clnte',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tpo_idntfcn',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='TipoCliente',
        ),
        migrations.DeleteModel(
            name='TipoId',
        ),
    ]
