# Generated by Django 3.0.3 on 2020-05-08 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_auto_20200507_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dscrpcn_tpo_clnte', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dscrpcn_tpo_idntfcn', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estrt_scl',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tpT_clnte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.TipoCliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tpo_idntfcn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.TipoId'),
        ),
    ]
